pipeline {
    agent any

    environment {
        // Define variables to store the repository URL and file path
        GIT_REPO = 'https://github.com/sabayneh1/cloudformation-templates.git'
        CLOUDFORMATION_FILE_PATH = 'cloudformation-templates/codes/code/3-parameters/1-ssm-parameters-hands-on.yaml'
        STACK_NAME = 'MyCloudFormationStackParamters' // Name of the CloudFormation stack
        REGION = 'ca-central-1' // Define AWS region to deploy
    }

    stages {
        stage('Checkout Code') {
            steps {
                // Pull the code from the specified GitHub repository
                git url: "${GIT_REPO}"
            }
        }

        stage('Test AWS Credentials') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-credentials' // Jenkins AWS credentials
                ]]) {
                    sh '''
                        # Test the AWS credentials by listing S3 buckets
                        aws s3 ls
                    '''
                }
            }
        }

        stage('Deploy CloudFormation Stack') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-credentials' // Jenkins AWS credentials
                ]]) {
                    sh '''
                        # Deploy the CloudFormation stack
                        aws cloudformation deploy \
                            --template-file ${CLOUDFORMATION_FILE_PATH} \
                            --stack-name ${STACK_NAME} \
                            --capabilities CAPABILITY_NAMED_IAM \
                            --region ${REGION}
                    '''
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished'
        }
    }
}
